# This is a basic workflow to help you get started with Actions
name: data

# Controls when the action will run. 
on:
  workflow_dispatch:

jobs:

  datasette:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - name: publishes to datasette
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            datasette
            sqlite-utils
            datasette-copyable
            csvs-to-sqlite
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Use gcloud CLI
        run: gcloud info
      - name: Set region
        run: gcloud config set run/region southamerica-east1

      - name: Deploy datasette
        run: |
          csvs-to-sqlite src/dbtools/*.csv backend
          datasette publish cloudrun backend.db --service=openpolitica-backend --install datasette-vega --install datasette-copyable
