name: deploy-staging
on:
  push:
    branches: [ develop ]  
jobs:
  build:
    name: deploy-staging
    runs-on: ubuntu-latest
    steps:
    - name: execute deployment script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.STAGING_HOST }}
        username: ${{ secrets.STAGING_USERNAME }}
        key: ${{ secrets.STAGING_KEY }}
        script: ./deployBackend.sh
